### ISSUE TITLE
api 出入参的优化建议

### ISSUE THREAD

**Issue by xuanyuan1hao** [yzcheng90/x_springboot-inteface-generatorper#1]
api的入参出参可以考虑用泛型，把对应的entity也加上标注，这样直接在swagger上面就能看到入参出参的具体指，而不是一个string类型的data就全部囊括了，这样生成的在线文档比较差，而根据swagger生成的静态文档就更差了。

**Comment by yzcheng90** [comment]
感谢建议，目前最新版本已使用entity  https://github.com/yzcheng90/X-SpringBoot
